import { Pitch, Booking, Team, Match, FinancialMetric } from '../types';

export const INITIAL_PITCHES: Pitch[] = [
  {
    id: 'pitch-1',
    name: 'Cancha 1 - La Bombonera',
    type: 'Fútbol 7',
    surface: 'Sintético Premium',
    pricePerHour: 650,
    nightPricePerHour: 780,
    isIndoor: false,
    hasLighting: true,
    status: 'Disponible',
    imageUrl: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?auto=format&fit=crop&q=80&w=800',
    features: ['Iluminación LED HD', 'Banca techada', 'Red de contención', 'Césped 50mm monofilamento'],
  },
  {
    id: 'pitch-2',
    name: 'Cancha 2 - Maracaná (Techada)',
    type: 'Fútbol 7',
    surface: 'Techado VIP',
    pricePerHour: 750,
    nightPricePerHour: 850,
    isIndoor: true,
    hasLighting: true,
    status: 'Ocupado',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800',
    features: ['Domo Antilluvia', 'Marcador Electrónico', 'Sonido Ambiente', 'Bancas acolchadas'],
  },
  {
    id: 'pitch-3',
    name: 'Cancha 3 - Camp Nou',
    type: 'Fútbol 7',
    surface: 'Césped Híbrido',
    pricePerHour: 600,
    nightPricePerHour: 720,
    isIndoor: false,
    hasLighting: true,
    status: 'Disponible',
    imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=800',
    features: ['Marcador LED', 'Cámara de Video Veo', 'Zona de Espectadores'],
  },
  {
    id: 'pitch-4',
    name: 'Cancha 4 - Wembley Express',
    type: 'Fútbol 5',
    surface: 'Sintético Premium',
    pricePerHour: 480,
    nightPricePerHour: 580,
    isIndoor: true,
    hasLighting: true,
    status: 'Disponible',
    imageUrl: 'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?auto=format&fit=crop&q=80&w=800',
    features: ['Formato 5v5 Rápido', 'Paredes acolchadas', 'Ideal Torneo Express'],
  },
];

const today = new Date().toISOString().split('T')[0];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-101',
    pitchId: 'pitch-2',
    pitchName: 'Cancha 2 - Maracaná (Techada)',
    customerName: 'Carlos Mendoza',
    customerPhone: '+52 55 1234 5678',
    customerEmail: 'carlos.mendoza@gmail.com',
    date: today,
    startTime: '19:00',
    endTime: '20:00',
    totalPrice: 850,
    depositPaid: 850,
    paymentStatus: 'Pagado Total',
    paymentMethod: 'Transferencia',
    status: 'Confirmada',
    teamA: 'Los Galácticos F7',
    teamB: 'Dep. La Gambeta',
    notes: 'Solicitan balón oficial #5 y petos verdes',
  },
  {
    id: 'bk-102',
    pitchId: 'pitch-1',
    pitchName: 'Cancha 1 - La Bombonera',
    customerName: 'Roberto Gómez',
    customerPhone: '+52 55 9876 5432',
    customerEmail: 'roberto@empresa.com',
    date: today,
    startTime: '20:00',
    endTime: '21:00',
    totalPrice: 780,
    depositPaid: 400,
    paymentStatus: 'Anticipo 50%',
    paymentMethod: 'Efectivo',
    status: 'Confirmada',
    teamA: 'Rayo Vallecano F7',
    teamB: 'Inter de Milán F7',
    notes: 'Liquida saldo restante en recepción antes del partido',
  },
  {
    id: 'bk-103',
    pitchId: 'pitch-3',
    pitchName: 'Cancha 3 - Camp Nou',
    customerName: 'Mariana Silva',
    customerPhone: '+52 55 5555 4444',
    date: today,
    startTime: '21:00',
    endTime: '22:00',
    totalPrice: 720,
    depositPaid: 0,
    paymentStatus: 'Pendiente',
    paymentMethod: 'Pendiente',
    status: 'Pendiente',
    teamA: 'Atlético San Pancho',
    teamB: 'Toros Neza',
  },
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: 'team-1',
    name: 'Los Galácticos F7',
    logo: '⚽',
    primaryColor: '#10b981',
    captainName: 'Carlos Mendoza',
    captainPhone: '5512345678',
    playersCount: 12,
    matchesPlayed: 7,
    wins: 5,
    draws: 1,
    losses: 1,
    goalsFor: 28,
    goalsAgainst: 14,
    points: 16,
    players: [
      { id: 'p1', name: 'Mateo Hernández', number: 10, position: 'Delantero', goals: 9, yellowCards: 1, redCards: 0 },
      { id: 'p2', name: 'Santiago Ruiz', number: 1, position: 'Portero', goals: 0, yellowCards: 0, redCards: 0 },
      { id: 'p3', name: 'Diego Torres', number: 5, position: 'Defensa', goals: 3, yellowCards: 2, redCards: 0 },
      { id: 'p4', name: 'Gael Morales', number: 8, position: 'Medio', goals: 6, yellowCards: 0, redCards: 0 },
    ],
  },
  {
    id: 'team-2',
    name: 'Dep. La Gambeta',
    logo: '🔥',
    primaryColor: '#f59e0b',
    captainName: 'Javier Navarro',
    captainPhone: '5588889999',
    playersCount: 11,
    matchesPlayed: 7,
    wins: 4,
    draws: 2,
    losses: 1,
    goalsFor: 22,
    goalsAgainst: 12,
    points: 14,
    players: [
      { id: 'p5', name: 'Rodrigo "El Rayo" Benítez', number: 7, position: 'Delantero', goals: 8, yellowCards: 1, redCards: 0 },
      { id: 'p6', name: 'Adrián Castillo', number: 4, position: 'Defensa', goals: 2, yellowCards: 3, redCards: 1 },
    ],
  },
  {
    id: 'team-3',
    name: 'Rayo Vallecano F7',
    logo: '⚡',
    primaryColor: '#ef4444',
    captainName: 'Roberto Gómez',
    captainPhone: '5598765432',
    playersCount: 10,
    matchesPlayed: 7,
    wins: 4,
    draws: 1,
    losses: 2,
    goalsFor: 19,
    goalsAgainst: 15,
    points: 13,
    players: [
      { id: 'p7', name: 'Alejandro Vega', number: 9, position: 'Delantero', goals: 7, yellowCards: 2, redCards: 0 },
    ],
  },
  {
    id: 'team-4',
    name: 'Inter de Milán F7',
    logo: '🛡️',
    primaryColor: '#06b6d4',
    captainName: 'Fernando Ibarra',
    captainPhone: '5544332211',
    playersCount: 12,
    matchesPlayed: 7,
    wins: 3,
    draws: 1,
    losses: 3,
    goalsFor: 16,
    goalsAgainst: 18,
    points: 10,
    players: [],
  },
  {
    id: 'team-5',
    name: 'Atlético San Pancho',
    logo: '🦁',
    primaryColor: '#8b5cf6',
    captainName: 'Hugo Sánchez Jr.',
    captainPhone: '5577665544',
    playersCount: 10,
    matchesPlayed: 7,
    wins: 2,
    draws: 1,
    losses: 4,
    goalsFor: 14,
    goalsAgainst: 20,
    points: 7,
    players: [],
  },
];

export const INITIAL_LIVE_MATCH: Match = {
  id: 'match-live-1',
  title: 'Gran Final Torneo Nocturno F7',
  teamA: {
    id: 'team-1',
    name: 'Los Galácticos F7',
    logo: '⚽',
    score: 3,
    color: '#10b981',
  },
  teamB: {
    id: 'team-2',
    name: 'Dep. La Gambeta',
    logo: '🔥',
    score: 2,
    color: '#f59e0b',
  },
  pitchId: 'pitch-2',
  pitchName: 'Cancha 2 - Maracaná (Techada)',
  date: today,
  time: '19:00',
  period: '2do Tiempo',
  timerSeconds: 1420, // 23:40 mins
  isTimerRunning: true,
  refereeName: 'Prof. Arturo Brizio',
  status: 'En Vivo',
  events: [
    { id: 'ev-1', minute: 8, type: 'Gol', team: 'A', playerName: 'Mateo Hernández' },
    { id: 'ev-2', minute: 14, type: 'Gol', team: 'B', playerName: 'Rodrigo Benítez' },
    { id: 'ev-3', minute: 22, type: 'Tarjeta Amarilla', team: 'B', playerName: 'Adrián Castillo' },
    { id: 'ev-4', minute: 28, type: 'Gol', team: 'A', playerName: 'Gael Morales' },
    { id: 'ev-5', minute: 34, type: 'Gol', team: 'B', playerName: 'Rodrigo Benítez' },
    { id: 'ev-6', minute: 41, type: 'Gol', team: 'A', playerName: 'Mateo Hernández' },
  ],
};

export const INITIAL_FINANCES: FinancialMetric = {
  totalRevenue: 28450,
  pendingCollect: 2350,
  totalBookings: 42,
  occupancyRate: 84,
  recentTransactions: [
    {
      id: 'tx-1',
      bookingId: 'bk-101',
      customer: 'Carlos Mendoza',
      pitchName: 'Cancha 2 - Maracaná',
      amount: 850,
      method: 'Transferencia',
      date: today,
      type: 'Pago Completo',
    },
    {
      id: 'tx-2',
      bookingId: 'bk-102',
      customer: 'Roberto Gómez',
      pitchName: 'Cancha 1 - La Bombonera',
      amount: 400,
      method: 'Efectivo',
      date: today,
      type: 'Anticipo',
    },
    {
      id: 'tx-3',
      bookingId: 'bk-099',
      customer: 'David Villa',
      pitchName: 'Cancha 3 - Camp Nou',
      amount: 720,
      method: 'Tarjeta',
      date: today,
      type: 'Pago Completo',
    },
  ],
};
